### ISSUE TITLE
Automated filling of form fields not reflected in model

### ISSUE THREAD

**Issue by timsayshey** [formvuelate/formvuelate#154] opened 2021-03-12 23:21 UTC
**Describe the bug**
When I fill fields in an automated way, the model doesn't get updated. Only when I manually type in the text input does the data get added to the model.

**Video**
![2021-03-12 17 19 54](https://user-images.githubusercontent.com/1148940/111008709-4e100c00-8357-11eb-8102-b992855aafc4.gif)

**To Reproduce**
1. Open the [example sandbox app](https://qtki6.csb.app/)
2. Install the [JunkFill Chrome extension](https://chrome.google.com/webstore/detail/junkfill/cajejbcjfkhgmfbapmhopccephhjedeb/related?hl=en) to simulate the autofill. 
3. While on the sandbox page, click the JunkFill extension icon.
4. Inspect the `modelValue` with Vue devtools and you will see that it doesn't reflect the text inputs.
5. Then type manually into the text inputs, you will then see it reflected in the `modelValue`

**Expected behavior**
I would expect the input data to show up in the model no matter how it is entered into the input, whether it be automated or manual entry.

**System Info**
- FormVueLate version: 2.2.1
- plugins being used with versions: none

**Comment by marina-mosti** [comment] 2021-03-13 08:34
Hello @timsayshey , this is not an issue with formvuelate but a known problem with chrome auto fill. You need to do some hacks on your components to listen to animations. Here's a link to read more 

https://github.com/vuejs/vue/issues/7058

**Comment by timsayshey** [comment] 2021-03-15 15:33
Hi @marina-mosti - That appears to be a separate issue. It's not the Chrome autofill that I'm using. I'm using an extension to fill the form with test data. It seems the Vue listener is broken. I wonder if this was introduced as a bug in Vue 3 since it was not an issue in Vue 2 with Vue Formulate which what I'm migrating from for Vue 3. I'm just looking for a workaround at this point. I'll update this ticket when I find a solution. Let me know if you have any ideas. Thanks!

**Comment by timsayshey** [comment] 2021-03-15 16:05
@marina-mosti Interesting. I created a normal form using the FormText component you provided and the form that isn't using FormVueLate works as expected with automated fill. However, the FormVueLate form does not, it only autofills the last field. I think there is something going on with the way it updates the model in FormVueLate.

Here's the updated Sandbox:
https://codesandbox.io/s/fvl-playground-forked-fqpfv

Here's a Chrome Extension that is working: (The other extension doesn't emit any events when it fills the form but this one does, ie click, blur, change) I confirmed this in the console:
https://chrome.google.com/webstore/detail/fake-filler/bnjjngeaknajbdcgpfkgnonkmififhfo?hl=en

Here's a new recording of the issue:
![2021-03-15 11 03 24](https://user-images.githubusercontent.com/1148940/111183755-41213180-857e-11eb-8827-114a2201cb9f.gif)

**Comment by timsayshey** [comment] 2021-03-15 16:10
@marina-mosti It looks like the object is not being passed around correctly which would be why the last entry overwrites all previous entries.

**Comment by timsayshey** [comment] 2021-03-15 16:11
Btw, this isn't just an issue for automated form filling. This will be a problem for e2e testing in tools like Cypress.

**Comment by marina-mosti** [comment] 2021-03-15 16:19
Hey @timsayshey 

It's hard to tell because the plugin doesn't have open-source, on how they're targeting inputs.
Saying that it will be a problem for e2e is also a stretch since most e2e software targets CSS selectors.

I did reproduce with your plugin, but unless they can help you figure out exactly what they're doing behind the scenes to set the value there's not much to be done here.

If you target the elements with JS and set the `value` and then `dispatchEvent` for change, you can see that v-model is working just fine.

```
temp1.value = 'first'
"first"
temp1.dispatchEvent(new Event('change'))
true
```

**Comment by marina-mosti** [comment] 2021-03-15 16:24
Re: If I had to guess, it would seem that the problem comes from the plugin firing off all the change events at the same time and it creates a race condition between the `v-model` bindings trying to update.

I just tested it out with FVL 3.x and with the new binding that I'm going to introduce this issue will be fixed.
Will have to wait for 3.x to be out of beta I think :) I don't see any feasible fix with 2.x with the current form model solution

**Comment by marina-mosti** [comment] 2021-03-15 16:25
Here's a 3.x code sandbox just in case: https://codesandbox.io/s/fvl-useschemaform-3x-w7i2f

**Comment by timsayshey** [comment] 2021-03-15 16:30
Awesome! Yes, I see it working in your V3 demo - I'll see if I can get my app upgraded to work with the V3 beta

**Comment by marina-mosti** [comment] 2021-03-15 16:31
The beta is pretty stable now I think, if you wanna check out the migration guide I have a PR open you can look at. It's pretty straight forward

**Closed as completed** 2021-03-15 16:37 UTC
